import type { GrowingProject } from "./growing-projects";
import type { Locale } from "./i18n";

type Introduction = {
  name: string;
  tagline: string;
  description: string;
  headline: [string, string];
  features: [string, string, string];
  details: [string, string, string];
  availability: string;
  privacy: string;
  caption: string;
};

function mapLocales<T>(transform: (locale: Locale) => T): Record<Locale, T> {
  return { ko: transform("ko"), en: transform("en"), ja: transform("ja") };
}

function introduce(options: {
  id: string;
  code: string;
  icon: string | null;
  version: string;
  platforms: string[];
  accent: GrowingProject["app"]["accent"];
  status: GrowingProject["app"]["status"];
  layout: GrowingProject["layout"];
  media?: GrowingProject["media"];
  copy: Record<Locale, Introduction>;
}): GrowingProject {
  const content = mapLocales((locale) => {
    const text = options.copy[locale];
    return { displayName: text.name, tagline: text.tagline, description: text.description, features: text.features };
  });
  const copy = mapLocales((locale) => {
    const text = options.copy[locale];
    return { headline: text.headline, featureDetails: text.details, availability: text.availability,
      privacy: text.privacy, mediaAlt: text.caption, mediaCaption: text.caption };
  });
  return {
    app: { id: options.id, detailPath: `apps/${options.id}/`, code: options.code, icon: options.icon,
      version: options.version, platforms: options.platforms, accent: options.accent, status: options.status, content, links: [] },
    layout: options.layout, media: options.media, copy,
  };
}

// Product facts verified against the local projects on 2026-10-05.
// No public download destination has been verified for these introductions.
export const additionalProjects: GrowingProject[] = [
  // Spotter is appended below to preserve the relative order of existing products.
  introduce({
    id: "beauty-touch", code: "PORTRAIT / ADJUST / COMPARE", icon: "app-icons/beauty-touch.png",
    version: "0.2.0", platforms: ["iPhone · iOS 17+"], accent: "apricot", status: "testing", layout: "phone",
    media: { src: "product-shots/beauty-touch/home.webp", width: 1206, height: 2622 },
    copy: {
      ko: { name: "Beauty Touch", tagline: "인물 사진을 조금씩 다듬고, 원본과 비교해요", description: "얼굴·체형·사진·머리 도구를 골라 강도를 조절하는 인물 사진 편집 앱입니다. 원본과 비교하며 편집하고, 프로젝트를 다시 열어 이어서 다듬어요.", headline: ["사진 속 나를,", "내가 원하는 만큼."], features: ["얼굴·체형·머리 보정", "원본 비교와 실행 취소", "프로젝트 보관과 사진 저장"], details: ["피부와 얼굴형, 체형, 머리색 등을 각각 조절해요. 필터와 자르기, 밝기 조절도 함께 사용할 수 있어요.", "같은 자르기와 회전 상태에서 원본을 비교하고, 실행 취소·다시 실행으로 조절 강도를 되돌릴 수 있어요.", "편집 프로젝트는 자동 저장하며, 사진 저장 시 원본 해상도로 다시 렌더링해요. 저장 이용권은 체험·구매 상태에 따라 달라져요."], availability: "0.2.0 내부 TestFlight 테스트 중입니다. 실제 인물 사진의 보정 품질과 고해상도 실기기 성능은 추가 검증 중이에요. 자동 물체 제거와 헤어스타일 생성은 지원하지 않아요.", privacy: "사진 분석과 보정은 기기 안에서 이뤄지고 원본 사진을 직접 바꾸지 않아요. 사진 보관함에 저장할 때 접근 권한을 사용합니다.", caption: "실제 개발 앱 홈 화면 · 테스트용 인물 그림이 담긴 편집 프로젝트" },
      en: { name: "Beauty Touch", tagline: "Refine a portrait, then compare it with the original", description: "Adjust face, body, photo, and hair tools at your own pace. Compare edits with the original and reopen a saved project to keep refining it.", headline: ["Your portrait,", "at your own touch."], features: ["Face, body, and hair adjustments", "Original comparison and undo", "Saved projects and photo export"], details: ["Adjust skin, face shape, body proportions, and hair color individually, alongside filters, cropping, and lighting controls.", "Compare with the original using the same crop and rotation. Undo and redo let you revisit each adjustment.", "Projects save automatically; photo export renders again at the original resolution. Export access depends on trial and purchase status."], availability: "Version 0.2.0 is in internal TestFlight testing. Real portrait quality and high-resolution device performance need further validation. Automatic object removal and hairstyle generation are not supported.", privacy: "Photo analysis and editing run on the device without modifying the original. Saving a result uses access to your photo library.", caption: "Actual development app home · editing projects with a synthetic portrait fixture" },
      ja: { name: "Beauty Touch", tagline: "人物写真を少しずつ整え、原本と比べる", description: "顔・体形・写真・髪のツールを選び、強さを調整する人物写真編集アプリ。原本と比較し、保存したプロジェクトで編集を続けられます。", headline: ["写真の自分を、", "好きな加減で。"], features: ["顔・体形・髪の調整", "原本比較と取り消し", "プロジェクト保存と写真出力"], details: ["肌、顔の形、体形、髪色を個別に調整。フィルター、切り抜き、明るさ調整も使えます。", "同じ切り抜きと回転で原本と比較し、取り消し・やり直しで調整を戻せます。", "プロジェクトを自動保存し、写真出力時は原本解像度で再描画します。出力は体験・購入状態に応じます。"], availability: "0.2.0を内部TestFlightでテスト中です。実際の人物写真の品質と高解像度の実機性能は検証中。自動物体除去や髪型生成には対応していません。", privacy: "写真の解析と編集は端末内で行い、原本を変更しません。結果の保存時は写真ライブラリへのアクセスを使います。", caption: "実際の開発版ホーム画面 · テスト用人物イラストの編集プロジェクト" },
    },
  }),
  introduce({
    id: "bluemoon", code: "WRITE / BUILD / PUBLISH", icon: "app-icons/bluemoon.png", version: "0.1.0",
    platforms: ["WINDOWS"], accent: "cobalt", status: "development", layout: "desktop",
    media: { src: "product-shots/bluemoon/characters.webp", width: 960, height: 720 },
    copy: {
      ko: { name: "블루문", tagline: "원고와 세계관을 한 작업실에서 이어 쓰는 소설 스튜디오", description: "회차와 장면을 쓰고 인물·장소·복선을 함께 정리하는 로컬 우선 소설 창작 스튜디오입니다. 원고의 버전과 삽화, 발행본을 한 작품 안에 모아요.", headline: ["이야기를 쓰고,", "그 세계를 이어가요."], features: ["회차·장면 집필과 집중 모드", "인물·세계관·복선 설정집", "버전 비교와 작품 백업"], details: ["작품 탐색기에서 회차와 장면을 정리하고, 분할 편집·검색·집중 모드로 원고를 이어 써요.", "인물과 장소, 사건과 복선을 정리하고 원고의 문장에 연결해요. 삽화 후보와 채택 이력도 작품에 보관합니다.", "스냅샷의 문단별 차이를 비교하고 복원해요. 작품 백업과 원고 출력, 별도의 발행본 보존도 제공합니다."], availability: "Windows 개발 버전입니다. 로컬 집필·설정·삽화·출력과 선택적 계정·작품별 수동 동기화 코드를 구현했습니다. 실제 서버 연결과 운영 환경의 다기기·출시 검증은 남아 있어요. 화면은 예제 작품의 브라우저 미리보기입니다.", privacy: "회원가입 없이 원고를 기기 안에 저장합니다. 선택적 AI 연결은 로컬 서비스 주소를 사용하며, 브라우저 미리보기와 Windows 앱의 저장소는 별개입니다.", caption: "개발 버전 브라우저 미리보기 · 예제 작품의 인물 설정 화면" },
      en: { name: "BlueMoon", tagline: "A writing studio for your manuscript and its world", description: "Write chapters and scenes while organizing characters, places, and foreshadowing. This local-first novel studio keeps revisions, illustrations, and publication records together.", headline: ["Write the story.", "Keep its world close."], features: ["Chapters, scenes, and focus mode", "Characters, worldbuilding, and plot threads", "Revision comparison and project backups"], details: ["Organize chapters and scenes in the binder. Continue writing with split editing, search, and a distraction-reducing focus mode.", "Connect characters, places, events, and plot threads to manuscript passages. Keep illustration candidates and selection history in the project.", "Compare paragraph changes between snapshots and restore a version. Back up a project, export manuscripts, and preserve publication copies separately."], availability: "A Windows development build. Local writing, worldbuilding, illustration management, export, and optional account/manual sync code are implemented. Live server connection and production multi-device/release validation remain. The image is a browser preview with a sample project.", privacy: "Manuscripts stay on the device without sign-up. Optional AI connects to a local service. Browser preview storage is separate from the Windows application's storage.", caption: "Development browser preview · character notes from a sample novel" },
      ja: { name: "BlueMoon", tagline: "原稿と世界観を一つの作業室で育てる小説スタジオ", description: "章や場面を執筆しながら、人物・場所・伏線を整理するローカル優先の小説制作アプリ。原稿の版、挿絵、公開時の記録を作品内にまとめます。", headline: ["物語を書いて、", "その世界を育てる。"], features: ["章・場面の執筆と集中モード", "人物・世界観・伏線の設定集", "版の比較と作品バックアップ"], details: ["章と場面を整理し、分割編集・検索・集中モードで執筆を続けます。", "人物・場所・出来事・伏線を原稿の文章につなぎ、挿絵候補と採用履歴も保管します。", "スナップショットの段落差分を比較・復元。作品のバックアップ、原稿出力、公開版の別途保存ができます。"], availability: "Windows開発版です。ローカル執筆・設定・挿絵・出力と、任意のアカウント・作品ごとの手動同期コードを実装。実際のサーバー接続、運用環境の複数端末・リリース検証は未完了です。画像はサンプル作品のブラウザプレビューです。", privacy: "登録なしで端末内に原稿を保存。任意のAI接続はローカルサービスを使います。ブラウザプレビューとWindows版の保存領域は別です。", caption: "開発版ブラウザプレビュー · サンプル小説の人物設定画面" },
    },
  }),
  introduce({
    id: "namu-note", code: "PLACE / CONNECT / KEEP", icon: "app-icons/namu-note.png", version: "0.1.0",
    platforms: ["WINDOWS", "iPhone", "iPad"], accent: "sprout", status: "development", layout: "desktop",
    media: { src: "product-shots/namu-note/canvas.webp", width: 1420, height: 920 },
    copy: {
      ko: { name: "나무 노트", tagline: "글과 자료를 자유롭게 놓고, 기기를 넘어 이어 쓰는 노트", description: "글 상자와 이미지, PDF를 원하는 자리에 놓는 자유 배치 노트입니다. Windows와 iPhone·iPad 편집기를 개발하며 iCloud Drive로 노트를 이어 쓰는 흐름을 만들고 있어요.", headline: ["생각이 놓이는 자리,", "자유롭게 이어지는 노트."], features: ["글·이미지·PDF 자유 배치", "분류·검색과 버전 복원", "원본 백업과 iCloud Drive 교환"], details: ["캔버스에 글과 자료를 놓고 위치와 크기를 바꿔요. Apple 앱에서는 손필기도 사용할 수 있어요.", "분류·태그·검색으로 찾고 버전의 차이를 비교해요. 복원한 내용은 새 사본으로 보존할 수 있습니다.", "노트를 원본 파일로 내보내고 새 사본으로 가져와요. iCloud Drive 전송 상태와 편집 충돌을 확인하며 다른 기기와 교환합니다."], availability: "개발 중입니다. Windows 저장과 실제 iCloud 업로드·재다운로드를 검증했습니다. Apple 편집기는 시뮬레이터에서 검사했으며 실제 iPad와 Windows 간 왕복 검증은 남아 있어요.", privacy: "노트와 첨부는 기기에 보관합니다. iCloud Drive 연결 시 파일이 사용자의 iCloud로 전송되며 다른 기기의 수신 완료와 로컬 전송 상태를 구분합니다.", caption: "실제 Windows 개발 앱 · 테스트 노트의 PDF와 객체 배치 화면" },
      en: { name: "Namu Note", tagline: "Place words and references freely; continue across devices", description: "Arrange text boxes, images, and PDFs wherever your thoughts fit. Windows and iPhone/iPad editors are being developed with a file exchange workflow through iCloud Drive.", headline: ["A place for your thoughts.", "Room to connect them."], features: ["Free placement of text, images, and PDFs", "Organization, search, and revision recovery", "Original backups and iCloud Drive exchange"], details: ["Move and resize text and references on the canvas. The Apple editor also supports handwriting.", "Find notes through categories, tags, and search. Compare revisions and restore content as a new copy.", "Export originals and import copies. Inspect iCloud Drive delivery and editing conflicts while exchanging notes with another device."], availability: "In development. Windows storage and real iCloud upload/download have been verified. The Apple editor has simulator coverage; a physical iPad-to-Windows round trip remains unverified.", privacy: "Notes and attachments are stored on your device. Connecting iCloud Drive sends files to your iCloud. Local delivery status is distinguished from receipt by another device.", caption: "Actual Windows development app · a test note with PDF and positioned objects" },
      ja: { name: "Namu Note", tagline: "文字と資料を自由に置き、端末を越えて書き続ける", description: "文字ボックス・画像・PDFを好きな場所に配置するノート。WindowsとiPhone・iPadの編集機能を開発し、iCloud Driveでノートをつなぐ仕組みを整えています。", headline: ["考えを置く場所。", "自由につながるノート。"], features: ["文字・画像・PDFの自由配置", "分類・検索と版の復元", "原本バックアップとiCloud Drive交換"], details: ["キャンバス上の文字や資料を移動・拡大縮小。Apple版では手書きも使えます。", "分類・タグ・検索で探し、版の差分を比較。復元した内容を新しいコピーとして残せます。", "原本を書き出してコピーを取り込み、iCloud Driveの転送状況や編集の競合を確認します。"], availability: "開発中です。Windows保存と実際のiCloudアップロード・再取得を検証。Apple版はシミュレータで確認し、実機iPadとWindowsの往復は未検証です。", privacy: "ノートと添付は端末内に保存。iCloud Drive接続時は利用者のiCloudに転送し、ローカル転送状況と別端末の受信完了を区別します。", caption: "実際のWindows開発版 · テストノートのPDFとオブジェクト配置画面" },
    },
  }),
  introduce({
    id: "drawing-ground", code: "DRAW / LAYER / KEEP", icon: "app-icons/drawing-ground.png", version: "0.1.0",
    platforms: ["iPad", "iPhone · iOS 18+"], accent: "leaf", status: "testing", layout: "tablet",
    media: { src: "product-shots/drawing-ground/canvas.webp", width: 2064, height: 2752 },
    copy: {
      ko: { name: "땅바닥", tagline: "넓은 캔버스에 손그림과 자료를 함께 놓아요", description: "iPad와 Apple Pencil을 중심으로 만든 로컬 드로잉 앱입니다. 무한 캔버스에 선과 이미지를 놓고, 속지와 레이어를 골라 그림을 쌓아갑니다.", headline: ["펜이 닿는 곳부터,", "나만의 땅바닥."], features: ["무한 캔버스와 속지", "브러시·이미지·레이어 편집", "PNG 출력과 원본 백업"], details: ["백지·줄노트·모눈·점선 속지를 고르고 이동·확대·회전하며 그려요. 문서마다 속지와 간격을 저장합니다.", "브러시와 굵기를 고르고 이미지와 선을 함께 이동·회전·확대해요. 레이어의 순서·잠금·불투명도를 조절할 수 있어요.", "전체 그림이나 선택 영역을 PNG로 내보내고 편집 가능한 원본을 백업·복원해요. 문서는 기기에 자동 저장합니다."], availability: "내부 TestFlight 테스트 중인 드로잉 프로토타입입니다. 실제 Pencil 입력과 대형 문서 성능은 추가 검증이 필요해요. 페이지 노트·텍스트 편집·PDF 출력은 아직 구현하지 않았습니다.", privacy: "서버나 계정 없이 문서를 기기 안에 저장합니다. 사진 선택기는 고른 사진만 읽고, 가져온 이미지는 문서에 복사해 보관합니다.", caption: "실제 iPad 개발 앱 화면 · 테스트 그림과 드로잉 도구" },
      en: { name: "Drawing Ground", tagline: "Bring drawings and references onto an open canvas", description: "A local drawing app centered on iPad and Apple Pencil. Place strokes and images on an infinite canvas and build a drawing with paper guides and layers.", headline: ["Where the pen lands,", "your ground begins."], features: ["Infinite canvas and paper guides", "Brushes, images, and layers", "PNG export and editable backups"], details: ["Choose blank, lined, grid, or dotted paper; pan, zoom, and rotate. Each document remembers its paper and spacing.", "Choose a brush and width, then move, rotate, and scale strokes with images. Adjust layer order, locking, and opacity.", "Export the whole drawing or a selection as PNG. Back up editable originals and restore them; documents save locally."], availability: "A drawing prototype in internal TestFlight testing. Physical Pencil input and large-document performance need validation. Page-based notes, text editing, and PDF export are not yet implemented.", privacy: "Documents stay on the device without a server or account. The photo picker reads selected photos only; imported images are copied into the document.", caption: "Actual iPad development app · a test drawing and drawing tools" },
      ja: { name: "Drawing Ground", tagline: "広いキャンバスに手描きと資料を一緒に置く", description: "iPadとApple Pencilを中心にしたローカル描画アプリ。無限キャンバスに線と画像を置き、用紙ガイドとレイヤーで絵を重ねていきます。", headline: ["ペンが触れる場所から、", "自分だけのキャンバス。"], features: ["無限キャンバスと用紙ガイド", "ブラシ・画像・レイヤー編集", "PNG出力と原本バックアップ"], details: ["白紙・罫線・方眼・ドットを選び、移動・拡大・回転しながら描きます。用紙と間隔を文書ごとに保存。", "ブラシと太さを選び、線と画像を一緒に移動・回転・拡大。レイヤーの順序・ロック・不透明度も調整できます。", "全体や選択範囲をPNGで出力。編集可能な原本をバックアップ・復元し、文書を端末に自動保存します。"], availability: "内部TestFlightでテスト中の描画プロトタイプです。実機Pencilと大きな文書の性能は要検証。ページ式ノート・文字編集・PDF出力は未実装です。", privacy: "サーバーや登録なしで端末に保存。写真選択は選んだ写真だけを読み、取り込んだ画像を文書内にコピーします。", caption: "実際のiPad開発画面 · テスト描画と描画ツール" },
    },
  }),
  introduce({
    id: "pretty-speech", code: "TYPE / REFINE / CHOOSE", icon: "app-icons/pretty-speech.png", version: "2.0.0",
    platforms: ["iPhone · iOS 26+", "KEYBOARD"], accent: "sky", status: "testing", layout: "workflow",
    copy: {
      ko: { name: "예쁘게 말하기", tagline: "보내기 전, 상대에게 맞는 말투를 골라요", description: "평소처럼 키보드로 입력하고 필요할 때만 AI로 말투를 다듬어요. 상사·고객·동료·친구·연인에 맞춰 제안을 살펴보고 마음에 드는 문장으로 직접 바꿉니다.", headline: ["같은 마음을,", "조금 더 알맞은 말로."], features: ["한국어·영어 키보드 입력", "상대와 스타일에 맞는 제안", "확인한 문장만 직접 적용"], details: ["두벌식 한글과 영어, 숫자·기호를 입력해요. 일반 입력과 말투 다듬기는 별개의 동작입니다.", "상대와 자연스럽게·부드럽게·간결하게 스타일을 고르면 기기 안의 모델이 문장을 제안해요.", "숫자와 날짜 등 원문 정보를 검사하고 사용자가 고른 제안만 적용해요. 생성 중 원문이 바뀌면 바로 덮어쓰지 않습니다."], availability: "2.0.0 내부 TestFlight 테스트 중입니다. 기기 내 소형 모델의 제안 품질은 문장에 따라 달라지며 조건을 통과한 제안이 적을 수 있어요. 메시지를 자동 전송하지 않습니다.", privacy: "말투 생성은 앱에 포함된 모델로 기기 안에서 처리하며 문장을 클라우드 생성 서비스에 보내지 않아요. 키보드의 전체 접근 권한 없이 동작하는 구성을 사용합니다.", caption: "사용 흐름 설명 · 입력 → 말투 제안 → 직접 선택, 앱 화면 아님" },
      en: { name: "Pretty Speech", tagline: "Choose a tone that fits the recipient before sending", description: "Type as usual and request an AI rewrite only when you need one. Review suggestions for a manager, customer, colleague, friend, or partner, then choose a sentence yourself.", headline: ["The same intention.", "A better-fitting tone."], features: ["Korean and English keyboard input", "Recipient-aware style suggestions", "Apply only the sentence you choose"], details: ["Type Korean, English, numbers, and symbols. Ordinary input and tone rewriting are separate actions.", "Select a recipient and a natural, softer, or concise style. A bundled on-device model proposes wording.", "Checks protect details such as numbers and dates. Choose a validated suggestion to apply; changes to the original stop stale replacements."], availability: "Version 2.0.0 is in internal TestFlight testing. Small on-device model quality varies, and fewer suggestions may pass validation. The keyboard does not send messages automatically.", privacy: "The bundled model generates on the device without sending text to a cloud generation service. The configuration works without keyboard Full Access.", caption: "Workflow explanation · type → review tone → choose; not an app screenshot" },
      ja: { name: "Pretty Speech", tagline: "送る前に、相手に合う言い方を選ぶ", description: "いつも通り入力し、必要なときだけAIで言い方を整えます。上司・顧客・同僚・友人・恋人向けの提案を確認し、自分で文章を選んで置き換えます。", headline: ["同じ気持ちを、", "相手に合う言葉で。"], features: ["韓国語・英語キーボード", "相手と文体に応じた提案", "選んだ文章だけを適用"], details: ["韓国語・英語・数字・記号を入力。通常入力と言い方の変更は別の操作です。", "相手と自然・柔らかい・簡潔な文体を選ぶと、端末内のモデルが表現を提案します。", "数字や日付などを検査し、選んだ提案だけを適用。生成中に原文が変わると上書きを止めます。"], availability: "2.0.0を内部TestFlightでテスト中。端末内の小型モデルの品質は文章によって変わり、検査を通る提案が少ない場合があります。自動送信はしません。", privacy: "同梱モデルが端末内で生成し、文章をクラウド生成サービスに送りません。キーボードのフルアクセスなしで動作する構成です。", caption: "利用フローの説明 · 入力→提案確認→選択、アプリ画面ではありません" },
    },
  }),
  introduce({
    id: "jamgyeol", code: "REST / LISTEN / REFLECT", icon: "app-icons/jamgyeol.png", version: "1.0",
    platforms: ["iPhone · iOS 18+", "HEALTHKIT"], accent: "amber", status: "testing", layout: "phone",
    media: { src: "product-shots/jamgyeol/journal.webp", width: 1320, height: 2868 },
    copy: {
      ko: { name: "잠결", tagline: "밤사이 소리와 건강 앱 기록을 한 일지에서", description: "밤사이 소리 기록과 건강 앱의 수면·심박 정보를 함께 돌아보는 수면 일지입니다. 생활 태그와 통계를 쌓고, 수면 보조 소리와 기상 알람을 준비해요.", headline: ["어젯밤의 흔적을,", "오늘의 일지로."], features: ["밤사이 소리 기록과 확인", "건강 앱 기록과 수면 일지", "생활 태그·통계와 알람"], details: ["마이크로 기록한 소리에서 분류된 구간을 살펴보고 직접 고쳐요. 기록된 범위와 분석하지 못한 구간을 구분합니다.", "권한을 준 건강 앱의 수면·심박·손목 온도를 소리 기록과 나란히 봐요. 건강 앱 원본을 수정하지 않아요.", "생활 태그와 주간 보고서로 기록을 돌아보고 수면 보조 소리와 기상 알람을 설정해요. 스마트 알람은 실험 기능입니다."], availability: "TestFlight 빌드를 올린 테스트 단계입니다. 실제 기기 야간 기록·알람과 코골이 분류 정확도는 검증 중이에요. 의료 진단용 제품이 아니며 화면의 수면 수치는 예시입니다.", privacy: "소리와 분석 기록은 기기에 보관합니다. 마이크와 건강 앱 읽기 권한은 사용자가 선택하며 건강 앱에 수면 데이터를 쓰지 않아요. 암호화 백업과 앱 잠금을 제공합니다.", caption: "실제 개발 앱 일지 화면 · 예시 수면 데이터, 의료 측정 결과 아님" },
      en: { name: "Jamgyeol", tagline: "Night sounds and Health records in one journal", description: "Review night-time sounds beside sleep and heart data from Health. Build a sleep journal with lifestyle tags and trends, and prepare sleep-aid sounds and a wake-up alarm.", headline: ["Last night's traces.", "Today's journal."], features: ["Record and review night sounds", "Health records alongside your journal", "Lifestyle tags, trends, and alarms"], details: ["Inspect classified sound intervals and correct them yourself. Recorded coverage is distinguished from intervals that could not be analyzed.", "Read permitted sleep, heart rate, and wrist temperature data from Health beside sound records, without changing the original Health data.", "Reflect with tags and weekly reports. Set sleep-aid sounds and a wake-up alarm; the smart alarm is experimental."], availability: "In testing with uploaded TestFlight builds. Real-device overnight recording, alarms, and snoring accuracy remain under validation. This is not a medical diagnostic product; displayed sleep values are examples.", privacy: "Audio and analysis stay on the device. Microphone and Health read permissions are optional; the app does not write sleep records to Health. Encrypted backups and app locking are provided.", caption: "Actual development journal screen · sample sleep data, not medical measurements" },
      ja: { name: "Jamgyeol", tagline: "夜の音とヘルスケア記録を一つの日誌で", description: "夜の音とヘルスケアの睡眠・心拍情報を振り返る睡眠日誌。生活タグや統計を積み重ね、睡眠補助音と起床アラームを準備できます。", headline: ["昨夜の手がかりを、", "今日の日誌に。"], features: ["夜の音を記録・確認", "ヘルスケアと睡眠日誌", "生活タグ・統計・アラーム"], details: ["分類された音の区間を確認し、手動で修正。記録できた範囲と分析できなかった区間を区別します。", "許可した睡眠・心拍・手首温度を音の記録と並べます。ヘルスケアの原本は変更しません。", "生活タグと週間報告で振り返り、補助音や起床アラームを設定。スマートアラームは実験的機能です。"], availability: "TestFlightビルドをアップロードしたテスト段階です。実機の夜間記録・アラーム・いびき分類精度は検証中。医療診断用ではなく、画面の睡眠値は例です。", privacy: "音と分析は端末内に保存。マイクとヘルスケア読み取り権限は任意で、睡眠記録を書き込みません。暗号化バックアップとアプリロックを提供します。", caption: "実際の開発版日誌 · 睡眠データの例、医療測定結果ではありません" },
    },
  }),
  introduce({
    id: "deepplayer", code: "SEEK / MARK / REVISIT", icon: "app-icons/deepplayer.png", version: "",
    platforms: ["WINDOWS"], accent: "cobalt", status: "development", layout: "workflow",
    copy: {
      ko: { name: "deepPlayer", tagline: "영상의 필요한 순간을 빠르게 찾고, 메모로 남겨요", description: "초 단위 탐색과 구간 반복을 중심으로 만든 Windows 로컬 동영상 플레이어입니다. 영상에 태그·시점 메모·북마크를 붙이고 검색 가능한 라이브러리로 모아요.", headline: ["다시 볼 그 순간,", "메모와 함께 찾아요."], features: ["초·프레임 탐색과 구간 반복", "시점 메모·태그·북마크", "폴더 라이브러리와 백업"], details: ["키보드로 초·프레임 단위로 이동하고 A–B 구간을 반복해요. 타임라인에서 썸네일과 마커를 확인합니다.", "현재 시점에 메모와 북마크를 남기고 태그와 평점으로 분류해요. 파일 이름과 메모를 함께 검색할 수 있어요.", "폴더를 라이브러리로 등록하고 필터를 컬렉션으로 저장해요. 메모·태그·북마크는 JSON 백업으로 내보냅니다."], availability: "Windows 로컬 개발 앱입니다. 실행 파일 빌드와 기본 미디어 앱 등록 기능을 구현했으나 공개 다운로드는 준비 중입니다. 영상 형식과 디코더에 따라 재생 동작이 달라질 수 있어요.", privacy: "영상은 로컬 파일에서 재생하고 태그·메모·북마크는 기기의 데이터베이스에 보관합니다. JSON 백업에는 메모와 파일 경로 정보가 포함됩니다.", caption: "사용 흐름 설명 · 영상 탐색 → 시점 기록 → 검색, 앱 화면 아님" },
      en: { name: "deepPlayer", tagline: "Find the moment you need and leave a note", description: "A Windows local video player built around precise seeking and interval loops. Add tags, timestamped notes, and bookmarks, then revisit them in a searchable library.", headline: ["Find that moment again.", "Keep its notes close."], features: ["Second/frame seeking and A–B loops", "Timestamped notes, tags, and bookmarks", "Folder library and metadata backups"], details: ["Seek by second or frame and repeat an A–B interval. Inspect thumbnails and markers along the timeline.", "Leave a note or bookmark at the current moment. Organize with tags and ratings; search filenames and note text together.", "Register folders and save filters as collections. Export notes, tags, and bookmarks as a JSON backup."], availability: "A local Windows development app. Executable builds and media-app registration are implemented; public downloads are not ready. Playback behavior can vary with format and decoder.", privacy: "Videos play from local files; notes, tags, and bookmarks stay in a local database. JSON backups include note contents and file paths.", caption: "Workflow explanation · seek video → mark a moment → search; not an app screenshot" },
      ja: { name: "deepPlayer", tagline: "必要な場面を素早く探し、メモで残す", description: "秒単位の移動と区間リピートを中心にしたWindowsローカル動画プレーヤー。タグ・時点メモ・ブックマークを付け、検索できるライブラリで振り返ります。", headline: ["もう一度見たい場面を、", "メモと一緒に探す。"], features: ["秒・フレーム移動と区間リピート", "時点メモ・タグ・ブックマーク", "フォルダ一覧とバックアップ"], details: ["秒・フレーム単位で移動しA–B区間を繰り返します。タイムラインのサムネイルとマーカーを確認できます。", "現在時点にメモとブックマークを残し、タグと評価で分類。ファイル名とメモを一緒に検索します。", "フォルダを登録し、フィルターをコレクションとして保存。メモ・タグ・ブックマークをJSONで出力します。"], availability: "Windowsローカル開発版です。実行ファイル生成とメディアアプリ登録を実装し、一般公開ダウンロードは準備中。形式やデコーダで動作が異なる場合があります。", privacy: "ローカル動画を再生し、メモ・タグ・ブックマークを端末DBに保存。JSONバックアップにはメモとファイルパスが含まれます。", caption: "利用フローの説明 · 動画移動→場面記録→検索、アプリ画面ではありません" },
    },
  }),
  introduce({
    id: "huntlog", code: "OBSERVE / TIME / REVIEW", icon: null, version: "0.2.0",
    platforms: ["WEB · DESKTOP"], accent: "amber", status: "testing", layout: "workflow",
    copy: {
      ko: { name: "HUNTLOG", tagline: "게임 화면을 직접 공유하고, 타이머와 세션을 기록해요", description: "사용자가 공유한 게임 화면에서 직접 고른 아이콘의 보임·사라짐을 관찰하는 로컬 우선 대시보드입니다. 예상 주기, 일반 타이머와 수동 경험치 기록을 함께 확인해요.", headline: ["플레이의 흐름을,", "기록으로 돌아봐요."], features: ["직접 고른 아이콘 최대 4개 관찰", "예상 주기와 일반 타이머", "수동 경험치와 세션 기록"], details: ["사용자가 화면을 공유하고 아이콘을 선택하면 모양을 기준으로 표시 상태를 살펴봐요. 스킬이나 게임 상황의 의미를 자동으로 이해하지 않습니다.", "직접 정한 예상 간격으로 주기 코치를 켜고 최대 12개 일반 타이머를 사용해요. 알림은 권한과 브라우저 지원에 따라 동작합니다.", "경험치를 직접 입력한 체크포인트로 증가 속도를 계산하고 세션의 상태·이벤트를 기록해요. 설정과 기록을 JSON으로 보관할 수 있어요."], availability: "공개 초기 알파를 목표로 개발·테스트 중이며 이 페이지에는 공개 실행 주소를 아직 등록하지 않았습니다. 판정은 화면 모양에 기반한 추정이에요. 게임 입력 생성·메모리·패킷 접근은 하지 않습니다.", privacy: "공유 화면은 브라우저에서 로컬 분석하며 시스템 오디오는 요청하지 않아요. IndexedDB에 설정·좌표·세션 메타데이터를 보관하며 진단 파일에는 화면 픽셀을 담지 않습니다.", caption: "사용 흐름 설명 · 화면 선택 → 아이콘 관찰 → 세션 기록, 앱 화면 아님" },
      en: { name: "HUNTLOG", tagline: "Share a game window and keep timers and session records", description: "A local-first dashboard that observes whether selected icons appear in a game window you share. Review expected cycles, general timers, and manually entered experience checkpoints.", headline: ["Follow the session.", "Review its rhythm."], features: ["Observe up to four selected icons", "Expected cycles and general timers", "Manual experience and session logs"], details: ["Share a window and select icons to observe by visual appearance. The app does not understand skill names or game-state meaning automatically.", "Set expected intervals for a cycle coach and use up to twelve general timers. Notifications depend on permissions and browser support.", "Enter experience checkpoints to estimate growth. Record session states and events, then export settings and records as JSON."], availability: "An early alpha project under development and testing; no public launch URL is registered here yet. Visual states are estimates. It does not generate game input or access game memory or packets.", privacy: "Shared frames are analyzed locally in the browser without requesting system audio. IndexedDB keeps settings, coordinates, and session metadata; diagnostics omit screen pixels.", caption: "Workflow explanation · choose a window → observe icons → log a session; not app UI" },
      ja: { name: "HUNTLOG", tagline: "ゲーム画面を共有し、タイマーとセッションを記録", description: "自分で共有したゲーム画面の選択アイコンを観察するローカル優先ダッシュボード。予想周期、一般タイマー、手入力の経験値を一緒に確認します。", headline: ["プレイの流れを、", "記録で振り返る。"], features: ["選んだ最大4アイコンを観察", "予想周期と一般タイマー", "手入力の経験値とセッション"], details: ["画面を共有し、選んだアイコンの形から表示状態を観察。スキル名やゲーム状況の意味は自動理解しません。", "自分で決めた間隔の周期通知と最大12個のタイマーを利用。通知は権限とブラウザ対応に依存します。", "経験値チェックポイントを手入力し増加速度を計算。状態とイベントを記録し、JSONで保存できます。"], availability: "初期アルファとして開発・テスト中で、ここには公開起動URLをまだ登録していません。画面判定は推定です。ゲーム入力生成・メモリ・パケットアクセスは行いません。", privacy: "共有画像をブラウザ内で解析し、システム音声は要求しません。設定・座標・記録をIndexedDBに保存し、診断には画面ピクセルを含めません。", caption: "利用フローの説明 · 画面選択→アイコン観察→記録、アプリ画面ではありません" },
    },
  }),
  introduce({
    id: "ai-ocr", code: "READ / TRANSCRIBE / REVIEW", icon: null, version: "",
    platforms: ["LOCAL API", "PDF / IMAGE"], accent: "cyan", status: "development", layout: "workflow",
    copy: {
      ko: { name: "ai-ocr", tagline: "문서 이미지와 스캔 PDF를 검수할 수 있는 Markdown으로", description: "손글씨와 소설·산문 원고를 대상으로 문서 이미지와 스캔 PDF를 전사하는 API 서비스입니다. 페이지별 텍스트를 합치고 사람이 확인할 페이지를 함께 남깁니다.", headline: ["사진 속 글을,", "다시 편집할 수 있게."], features: ["이미지·스캔 PDF 전사", "고유명사와 원문 표기 보존 옵션", "Markdown과 검수 대상 목록"], details: ["문서를 페이지로 나눠 전사하고 합쳐요. 텍스트 레이어가 충분한 PDF는 기존 텍스트를 먼저 사용합니다.", "인물과 지명의 용어집을 넘기고 원문 표기 보존 옵션을 선택해요. 고유명사 오독을 줄이는 보조 정보입니다.", "생략·반복·판독 실패를 점검하고 필요한 페이지를 재시도해요. 최종 Markdown과 사람이 확인할 페이지 목록을 제공합니다."], availability: "로컬 API 개발 프로젝트로 공개 업로드 서비스는 아직 없습니다. 비전 모델 전사는 잘못 읽거나 생략할 수 있으므로 원문 대조가 필요해요. 처리 비용은 연결한 모델 서비스 사용량에 따라 발생합니다.", privacy: "이미지 전사가 필요한 페이지는 설정한 외부 모델 API로 전송됩니다. 문서의 보관과 처리 범위는 운영 환경에서 설정하며, 민감한 원고의 전송 여부를 먼저 확인해야 합니다.", caption: "처리 흐름 설명 · 문서 입력 → 페이지 전사 → Markdown 검수, 앱 화면 아님" },
      en: { name: "ai-ocr", tagline: "Turn document images and scanned PDFs into reviewable Markdown", description: "An API for transcribing handwriting, novel manuscripts, and prose from images or scanned PDFs. Merge page text while keeping a list of pages that need human review.", headline: ["Words in a photograph.", "Text you can edit again."], features: ["Image and scanned-PDF transcription", "Glossaries and original spelling options", "Markdown with a review-page list"], details: ["Split documents into pages, transcribe, and merge. PDFs with sufficient existing text use that layer first.", "Supply a glossary of character and place names and choose spelling preservation. These support better transcription of unusual terms.", "Check for omission, repetition, and unreadable text; retry flagged pages. Receive Markdown and a human-review list."], availability: "A local API development project without a public upload service. Vision transcription may misread or omit text, so compare with the source. Connected model API usage incurs costs.", privacy: "Pages needing image transcription are sent to the configured external model API. Retention and processing depend on the deployment; review transmission before handling sensitive manuscripts.", caption: "Processing explanation · document → page transcription → Markdown review; not app UI" },
      ja: { name: "ai-ocr", tagline: "文書画像とスキャンPDFを確認できるMarkdownに", description: "手書きや小説・散文の原稿を画像・スキャンPDFから文字に起こすAPI。ページの文章をまとめ、人が確認すべきページも一覧に残します。", headline: ["写真の中の言葉を、", "編集できる文章へ。"], features: ["画像・スキャンPDFの文字起こし", "用語集と原文表記の保持設定", "Markdownと確認ページ一覧"], details: ["文書をページに分けて文字に起こし、結合します。十分なテキスト層があるPDFは既存の文字を優先します。", "人物・地名の用語集と表記保持を設定。珍しい固有名詞の読み取りを補助します。", "省略・繰り返し・判読失敗を確認し再試行。Markdownと人が確認するページ一覧を出力します。"], availability: "ローカルAPIの開発版で、一般公開のアップロードサービスはありません。誤読・省略があり得るため原文との照合が必要です。接続先モデルAPIの利用費用が発生します。", privacy: "画像解析が必要なページを設定した外部モデルAPIへ送信します。保存・処理範囲は運用環境によるため、機密原稿は送信条件を先に確認してください。", caption: "処理フローの説明 · 文書→ページ文字起こし→Markdown確認、アプリ画面ではありません" },
    },
  }),
  introduce({
    id: "autotrade", code: "RESEARCH / SIMULATE / REVIEW", icon: null, version: "0.2.0",
    platforms: ["WINDOWS", "LOCAL DASHBOARD"], accent: "sky", status: "development", layout: "workflow",
    copy: {
      ko: { name: "AutoTrade", tagline: "공개 시세에서 모델을 연구하고, 모의계좌로 비교해요", description: "공개 시세 수집과 모델 학습, 후보별 모의 운용을 연결하는 로컬 연구 시스템입니다. 평가 결과와 운용 기록을 대시보드에서 확인하고 승인한 모델을 모의계좌에 적용합니다.", headline: ["시세에서 배우고,", "모의 운용으로 확인해요."], features: ["공개 시세 수집과 모델 학습", "후보별 모의계좌와 비교 평가", "로컬 승인·손실 한도·기록"], details: ["시세에서 경험 데이터를 만들고 시간순으로 학습·검증해요. 거래비용을 반영한 비교 평가를 남깁니다.", "모델 후보마다 독립 모의계좌를 두고 현금·단순 보유 등의 기준과 비교해요. 모의 결과는 실제 수익을 보장하지 않습니다.", "대시보드에서 기록과 한도를 확인하고 모델을 승인·중지·되돌려요. 실제 주문 경로는 별도의 승인과 시작 조건을 갖습니다."], availability: "0.2.0 개발 버전으로 공개 시세 연구와 모의 운용만 실행 중입니다. 실제 계좌·주문 통합 검증은 수행하지 않았습니다. 투자 수익이나 실거래 안정성을 약속하는 서비스가 아닙니다.", privacy: "모델·평가·거래 기록을 로컬에 보관하고 공개 시세는 외부 거래소에서 받습니다. 실제 계좌 연결 시 해당 거래소 API를 사용하며 키는 Windows 사용자 암호화 저장소에 보관합니다.", caption: "연구 흐름 설명 · 공개 시세 → 모델 평가 → 모의계좌, 앱 화면 아님" },
      en: { name: "AutoTrade", tagline: "Research market models and compare them in paper accounts", description: "A local research system connecting public market data, model training, and independent candidate paper accounts. Review evaluations and records in a dashboard before approving a model for simulation.", headline: ["Learn from market data.", "Check it in simulation."], features: ["Public market data and model training", "Independent paper accounts and comparisons", "Local approvals, limits, and records"], details: ["Build experiences from market data and evaluate with chronological splits. Keep comparisons that include trading costs.", "Give candidates separate paper accounts and compare them with cash and simple-hold baselines. Simulated results do not guarantee real returns.", "Review logs and limits, approve or pause a model, and roll back. Real-order code has separate approval and startup conditions."], availability: "Version 0.2.0 is in development, running public-data research and paper trading only. Real-account/order integration has not been validated. This project does not promise investment returns or live-trading reliability.", privacy: "Models, evaluations, and records stay local; public prices come from external exchanges. Account connections use exchange APIs; keys use Windows user-bound encrypted storage.", caption: "Research flow explanation · market data → model evaluation → paper account; not app UI" },
      ja: { name: "AutoTrade", tagline: "公開相場でモデルを研究し、模擬口座で比較する", description: "公開相場の収集・モデル学習・候補別模擬運用をつなぐローカル研究システム。評価と運用記録を確認し、承認したモデルを模擬口座に適用します。", headline: ["相場から学び、", "模擬運用で確かめる。"], features: ["公開相場収集とモデル学習", "候補別模擬口座と比較評価", "ローカル承認・損失上限・記録"], details: ["相場から経験データを作り、時系列で学習・検証。取引費用を含む比較を残します。", "候補ごとに模擬口座を用意し、現金・単純保有などと比較。模擬結果は実際の利益を保証しません。", "記録と上限を確認し、承認・停止・巻き戻しを行います。実注文には別途承認と開始条件があります。"], availability: "0.2.0開発版で、公開相場研究と模擬運用だけを実行中。実口座・注文の統合検証は未実施です。投資利益や実取引の信頼性を約束するサービスではありません。", privacy: "モデル・評価・記録をローカル保存し、公開相場は外部取引所から取得。口座接続は取引所APIを使い、鍵はWindowsユーザーに結び付く暗号化領域に保存します。", caption: "研究フローの説明 · 公開相場→モデル評価→模擬口座、アプリ画面ではありません" },
    },
  }),
  introduce({
    id: "spotter", code: "CAMERA / MOTION / LOG", icon: "app-icons/spotter.png", version: "1.0.0",
    platforms: ["iPhone"], accent: "apricot", status: "testing", layout: "workflow",
    copy: {
      ko: { name: "Spotter", tagline: "카메라로 운동 동작을 살펴보고, 횟수와 세트를 기록해요", description: "iPhone 카메라의 자세 분석으로 운동 반복과 휴식 후 세트 구분을 돕는 운동 기록 앱입니다. 자동 종목 이름과 기록을 직접 고칠 수 있고, 카메라 없이 운동을 수동으로 기록할 수도 있어요.", headline: ["휴대폰을 놓고 운동해요.", "횟수와 기록은 함께."], features: ["기기 내 자세 분석과 반복 세기", "종목·횟수 수정과 수동 기록", "월별 운동 기록과 Apple 건강 가져오기"], details: ["카메라에서 몸의 관절과 움직임을 분석해 반복을 세고 휴식 뒤 세트를 나눠요. 자동 종목 분류는 실험 단계이며 모호한 동작은 미확정으로 남길 수 있어요.", "잘못 알아본 종목 이름과 반복 횟수를 직접 고쳐요. 수동 기록에서는 날짜, 세트, 반복, 선택적 무게와 메모를 입력할 수 있어요.", "최근 운동과 월별 캘린더에서 기록을 다시 봐요. iPhone에서는 허용한 Apple 건강 운동을 읽어 가져오며, 가져온 운동의 거리·시간과 Spotter의 반복 기록을 구분합니다."], availability: "1.0.0 내부 TestFlight 테스트 단계입니다. 공개 설치 링크는 아직 준비 중입니다. 자동 운동 분류와 실기기 인식 품질은 검증을 이어가며, 카메라 엔진은 지원하는 iPhone 네이티브 빌드에서 사용합니다.", privacy: "자세 분석은 기기 안에서 처리하고 운동 기록은 로컬 SQLite에 저장합니다. 일반 운동 촬영은 이미지를 저장하거나 업로드하지 않습니다. 별도로 켠 내부 기구 학습 모드는 대표 이미지를 기기에 저장할 수 있어요. Apple 건강 가져오기는 읽기 권한만 사용합니다.", caption: "기능 흐름 설명 · 실제 카메라 화면이나 인식 실행 결과가 아닙니다" },
      en: { name: "Spotter", tagline: "Follow exercise movements, then log repetitions and sets", description: "An iPhone workout journal that uses on-device pose analysis to help count repetitions and separate sets after rest. Correct exercise names and records yourself, or log a workout manually without the camera.", headline: ["Set down your phone.", "Keep moving, keep a record."], features: ["On-device pose analysis and rep counting", "Label corrections and manual workouts", "Monthly journal and Apple Health import"], details: ["Analyze body joints and movement to count repetitions and separate sets after rest. Exercise classification is experimental and can leave ambiguous movements provisional or unknown.", "Correct exercise names and repetitions. Manual entries support dates, sets, repetitions, optional weights, and notes.", "Revisit recent workouts and the monthly calendar. With permission, read workouts from Apple Health, keeping their distance and duration distinct from Spotter repetitions."], availability: "Version 1.0.0 is in internal TestFlight testing; a public installation link is not available yet. Exercise classification and device recognition quality remain under validation. The camera engine requires a supported native iPhone build.", privacy: "Pose analysis runs on-device and records stay in local SQLite. Normal workout capture does not save or upload images. A separately enabled internal equipment-learning mode may save representative images locally. Apple Health import uses read-only access.", caption: "Feature flow explanation · not a camera screen or recognition run result" },
      ja: { name: "Spotter", tagline: "カメラで運動の動きを捉え、回数とセットを記録", description: "iPhoneの端末内姿勢解析で運動の反復回数や休憩後のセット区切りを助ける運動記録アプリ。自動の種目名や記録を修正でき、カメラなしで手動記録もできます。", headline: ["スマートフォンを置いて、", "運動と記録を続けよう。"], features: ["端末内の姿勢解析と回数カウント", "種目・回数の修正と手動記録", "月別の運動記録とAppleヘルスケア読み込み"], details: ["関節と動きを解析して反復を数え、休憩後にセットを区切ります。種目分類は実験段階で、曖昧な動きは暫定・不明として扱えます。", "種目名や回数を修正。手動記録では日付、セット、回数、任意の重量やメモを入力できます。", "最近の運動と月別カレンダーで振り返ります。許可したAppleヘルスケアの運動を読み込み、距離・時間とSpotterの反復記録を区別します。"], availability: "1.0.0の内部TestFlightテスト段階で、一般向けインストールリンクは準備中です。種目分類と実機の認識品質は検証中。カメラエンジンには対応するiPhoneネイティブビルドが必要です。", privacy: "姿勢解析は端末内、記録はローカルSQLiteに保存。通常の撮影では画像を保存・アップロードしません。別途有効にした内部の器具学習モードは代表画像を端末に保存する場合があります。ヘルスケアは読み取り専用です。", caption: "機能の流れの説明 · カメラ画面や認識の実行結果ではありません" },
    },
  }),
];
