import { productApps } from "./apps";
import type { Locale } from "./i18n";

export const productivityAppIds = ["ssakmemo", "namu-note", "drawing-ground", "timeflower"] as const;
// This is an editorial collection, independent of catalog order and purpose filters.
export const productivityApps = productivityAppIds.map((id) => productApps.find((app) => app.id === id)!);

export const productivityCopy = {
  ko: { pageTitle: "작은 도구의 생태계 | HIORIO 생산성 보조 도구", title: "생산성을 돕는 작은 도구들", description: "싹 메모, 나무 노트, 땅바닥, TimeFlower. 기록하고 생각을 펼치고 일정을 정리하는 네 가지 독립 앱을 모았습니다.", short: "메모부터 생각 정리, 그림과 일정까지. 필요한 순간에 골라 쓰는 네 가지 도구입니다.", open: "생산성 도구 모음 보기", all: "전체 앱 보기", headline: ["기록하고 정리하는,", "작은 도구의 생태계."], intro: "싹, 나무, 땅과 꽃. 자연을 담은 이름 아래, 일상의 생각과 일을 도와주는 앱을 모았습니다. 각 앱은 독립적으로 사용할 수 있습니다.", about: "앱 소개 보기", roles: ["떠오른 생각 붙잡기", "생각의 자리 만들기", "그림으로 생각 펼치기", "함께 일정 정리하기"], note: "각 앱의 기능과 출시 상태는 서로 다릅니다. 이 모음은 쓰임을 기준으로 묶은 소개이며, 앱 사이의 자동 연동을 의미하지 않습니다.", footer: "나에게 필요한 도구부터, 하나씩." },
  en: { pageTitle: "An ecosystem of small tools | HIORIO productivity helpers", title: "Small tools for getting things done", description: "Ssak Memo, Namu Note, Drawing Ground, and TimeFlower: four independent apps for capturing notes, exploring ideas, drawing, and organizing schedules.", short: "Notes, ideas, drawings, and schedules. Four independent tools to choose from as you need them.", open: "Explore the productivity collection", all: "See all apps", headline: ["Capture. Explore. Organize.", "An ecosystem of small tools."], intro: "Sprouts, trees, ground, and flowers: nature-inspired names for apps that help with everyday ideas and tasks. Each app can be used independently.", about: "About this app", roles: ["Capture a passing thought", "Give your ideas a place", "Think through drawing", "Organize schedules together"], note: "Features and availability differ by app. This collection groups related uses; it does not imply automatic integration between apps.", footer: "Start with the tool you need today." },
  ja: { pageTitle: "小さな道具の生態系 | HIORIO 生産性サポート", title: "毎日の作業を助ける小さな道具", description: "Ssak Memo、Namu Note、Drawing Ground、TimeFlower。記録・思考整理・描画・予定管理を助ける四つの独立したアプリを集めました。", short: "メモ、思考整理、絵、予定。必要なときに選んで使う四つの道具です。", open: "生産性ツールのコレクションを見る", all: "すべてのアプリを見る", headline: ["記録し、考え、整える。", "小さな道具の生態系。"], intro: "芽、木、大地、花。自然を込めた名前のもとに、日々の考えや作業を助けるアプリを集めました。それぞれ独立して使えます。", about: "アプリの紹介を見る", roles: ["浮かんだ考えをつかまえる", "考えを置く場所をつくる", "描きながら考える", "一緒に予定を整理する"], note: "機能と公開状況はアプリによって異なります。用途でまとめたコレクションであり、アプリ間の自動連携を意味しません。", footer: "今日必要な道具から、一つずつ。" },
} satisfies Record<Locale, { [key: string]: string | string[] }>;
