import type { Locale } from "./i18n";

export const ringtoneCopy = {
  ko: {
    pageTitle: "벨소리로 | 좋아하는 소리의 한 구간을 벨소리로",
    pageDescription: "음악 파일에서 마음에 드는 최대 30초를 골라 iPhone 벨소리 파일로. 파형 편집, 반복 미리 듣기, 페이드 효과까지 기기 안에서 처리하는 벨소리로.",
    name: "벨소리로", status: "운영 중", eyebrow: "내 음악으로 만드는 iPhone 벨소리",
    headline: ["좋아하는 소리의", "딱 그 부분만,", "벨소리로."],
    intro: "한 곡을 다 담을 필요는 없으니까요. 내 음악 파일에서 마음에 드는 구간을 골라, 전화가 올 때마다 듣고 싶은 소리로 만들어보세요.",
    store: "App Store에서 받기", explore: "만드는 과정 보기", meta: "무료 · iPhone · iOS 26 이상",
    previewLabel: "원하는 구간을 골라보세요", previewNote: "기능을 설명하는 예시예요. 실제 음원은 재생되지 않아요.",
    duration: "선택한 길이", seconds: "초", range: "구간 선택", presets: ["앞부분", "가운데", "뒷부분"],
    selection: "선택 구간", start: "시작", end: "끝", exportLabel: "나만의 벨소리 파일", exportNote: "M4A · 최대 30초",
    promises: ["0.1초 단위로 섬세하게", "반복해서 미리 듣기", "시작과 끝을 부드럽게"],
    processLabel: "소리 하나가 벨소리가 되기까지", processTitle: "고르고, 다듬고,\n내 벨소리로.",
    processIntro: "복잡한 편집 도구 대신, 벨소리에 필요한 것만 담았습니다.",
    screenshotCaption: "실제 앱 시작 화면 · 상단", screenshotAlt: "벨소리로 실제 시작 화면. 음악 파일 선택 버튼과 최근 만든 벨소리 목록.",
    steps: [
      { title: "내 파일에서 소리를 가져와요", body: "파일 앱이나 iCloud Drive에 있는 MP3, M4A, AAC, WAV 파일을 선택하세요. 사용 권한이 있는, DRM 없는 오디오가 필요해요.", note: "MP3 / M4A / AAC / WAV" },
      { title: "듣고 싶은 부분만 남겨요", body: "전체 파형을 보며 최대 30초를 고르세요. 0.1초 단위로 조절하고 반복해서 들으며, 페이드 인·아웃으로 양 끝을 다듬을 수 있어요.", note: "구간 선택 · 반복 재생 · 페이드" },
      { title: "파일로 만들고, 벨소리로 써요", body: "완성한 M4A 파일을 저장하거나 iPhone 공유 메뉴로 보내세요. 마지막 벨소리 적용은 공유 메뉴에서 직접 완료합니다.", note: "저장 · iPhone 공유 메뉴" },
    ],
    privacyLabel: "내 소리는, 내 iPhone 안에서", privacyTitle: "음악 파일을\n맡기지 않아도 돼요.",
    privacyBody: "파형 분석부터 편집, 미리 듣기, 내보내기까지 iPhone 안에서 처리합니다. 오디오를 개발자 서버로 보내지 않고, 회원가입이나 광고·추적 SDK도 넣지 않았습니다.",
    privacyTags: ["계정 없이", "서버 업로드 없이", "광고·추적 없이"],
    faqTitle: "시작하기 전에", faqs: [
      { question: "스트리밍 앱의 음악도 가져올 수 있나요?", answer: "DRM으로 보호된 스트리밍 음악은 편집할 수 없습니다. 사용자가 보유하고 사용 권한이 있는 MP3, M4A, AAC, WAV 등 DRM 없는 오디오 파일을 준비해 주세요." },
      { question: "앱에서 바로 벨소리가 바뀌나요?", answer: "앱은 벨소리 파일을 만들고 iPhone 공유 메뉴로 전달합니다. 시스템 벨소리를 자동으로 변경하지 않으며, 최종 적용은 공유 메뉴에서 사용자가 직접 진행합니다. 표시되는 항목은 iOS와 기기 환경에 따라 달라질 수 있습니다." },
      { question: "어떤 기기에서 사용할 수 있나요?", answer: "iOS 26 이상이 설치된 iPhone에서 무료로 사용할 수 있습니다. 만든 파일은 M4A 형식으로 저장되며, 선택할 수 있는 구간은 최대 30초입니다." },
    ],
    finalTitle: "다음 전화는,\n내가 고른 소리로.", support: "사용 안내", privacy: "개인정보 처리방침", back: "틔운 앱들로 돌아가기",
  },
  en: {
    pageTitle: "Make It a Ringtone | Keep the part you love",
    pageDescription: "Choose up to 30 seconds from your own audio for an iPhone ringtone file. Trim a waveform, loop a preview, and add fades, all on your device.",
    name: "Make It a Ringtone", status: "Available now", eyebrow: "An iPhone ringtone, made from your music",
    headline: ["Your favorite sound.", "Just the good part.", "Your ringtone."],
    intro: "You don’t need the whole song. Pick the part you love from an audio file you own and make it the sound you want to hear when a call comes in.",
    store: "Get it on the App Store", explore: "See how it works", meta: "Free · iPhone · iOS 26 or later",
    previewLabel: "Choose your favorite part", previewNote: "An illustration of segment selection. No audio is played here.",
    duration: "Selected duration", seconds: "sec", range: "Choose a segment", presets: ["Beginning", "Middle", "End"],
    selection: "Selected segment", start: "Start", end: "End", exportLabel: "Your own ringtone file", exportNote: "M4A · Up to 30 seconds",
    promises: ["Fine-tune in 0.1-second steps", "Loop your preview", "Fade in. Fade out."],
    processLabel: "From a sound to your ringtone", processTitle: "Pick it. Trim it.\nMake it yours.",
    processIntro: "The tools you need for a ringtone, without a complicated editor.",
    screenshotCaption: "Actual app home screen · upper section", screenshotAlt: "Actual Make It a Ringtone home screen showing audio import and recent ringtones.",
    steps: [
      { title: "Start with an audio file you own", body: "Choose an MP3, M4A, AAC, or WAV file from Files or iCloud Drive. Use DRM-free audio that you have permission to use.", note: "MP3 / M4A / AAC / WAV" },
      { title: "Keep the part you want to hear", body: "Use the full waveform to choose up to 30 seconds. Fine-tune in 0.1-second steps, loop your preview, and soften the edges with fade-in and fade-out.", note: "Select · Loop · Fade" },
      { title: "Export it, then set your ringtone", body: "Save the finished M4A file or send it to the iPhone share menu. You complete the final ringtone assignment yourself from that menu.", note: "Save · iPhone share menu" },
    ],
    privacyLabel: "Your sounds stay on your iPhone", privacyTitle: "Your music doesn’t\nneed our servers.",
    privacyBody: "Waveform analysis, editing, preview, and export all happen on your iPhone. Audio is not sent to developer servers. No account, advertising, or tracking SDKs.",
    privacyTags: ["No account", "No server uploads", "No ads or tracking"],
    faqTitle: "Before you start", faqs: [
      { question: "Can I import music from a streaming app?", answer: "DRM-protected streaming music cannot be edited. Use DRM-free audio files you own and have permission to use, such as MP3, M4A, AAC, or WAV." },
      { question: "Does the app change my ringtone automatically?", answer: "The app creates a ringtone file and sends it to the iPhone share menu. It cannot change the system ringtone automatically; you finish the assignment yourself. Available share actions can vary by iOS version and device environment." },
      { question: "Which devices are supported?", answer: "The app is free on iPhone with iOS 26 or later. Files are exported as M4A, with a selection of up to 30 seconds." },
    ],
    finalTitle: "Let the next call\nsound like you.", support: "How to use", privacy: "Privacy policy", back: "Back to the apps",
  },
  ja: {
    pageTitle: "Hiorio 着信音メーカー | 好きな音の、好きな部分を",
    pageDescription: "自分の音声ファイルから好きな最大30秒を選んで、iPhoneの着信音ファイルに。波形編集、リピート試聴、フェードを端末内で処理します。",
    name: "Hiorio 着信音メーカー", status: "公開中", eyebrow: "自分の音楽からつくるiPhoneの着信音",
    headline: ["好きな音の、", "好きなところを。", "私の着信音に。"],
    intro: "曲をまるごと使わなくてもいい。手元の音声ファイルからお気に入りの部分を選んで、電話が来るたびに聴きたい音にしてみましょう。",
    store: "App Storeでダウンロード", explore: "つくり方を見る", meta: "無料 · iPhone · iOS 26以降",
    previewLabel: "好きな範囲を選んでみよう", previewNote: "範囲選択を説明するイメージです。音声は再生されません。",
    duration: "選択した長さ", seconds: "秒", range: "範囲を選択", presets: ["最初", "中央", "最後"],
    selection: "選択範囲", start: "開始", end: "終了", exportLabel: "自分だけの着信音ファイル", exportNote: "M4A · 最大30秒",
    promises: ["0.1秒単位で細かく調整", "繰り返して試聴", "始まりと終わりをなめらかに"],
    processLabel: "ひとつの音が着信音になるまで", processTitle: "選んで、整えて。\n自分の着信音に。",
    processIntro: "複雑な編集ツールではなく、着信音に必要な機能をまとめました。",
    screenshotCaption: "実際のアプリ開始画面 · 上部", screenshotAlt: "音声ファイル選択と最近作成した着信音が表示された実際の開始画面。",
    steps: [
      { title: "手元のファイルから音を選ぶ", body: "ファイルやiCloud DriveからMP3、M4A、AAC、WAVを選択。利用許可のある、DRMフリーの音声を用意してください。", note: "MP3 / M4A / AAC / WAV" },
      { title: "聴きたい部分だけを残す", body: "全体の波形を見ながら最大30秒を選択。0.1秒単位で調整し、繰り返して試聴。フェードイン・アウトで両端を整えられます。", note: "範囲選択 · リピート · フェード" },
      { title: "保存して、着信音にする", body: "完成したM4Aファイルを保存するか、iPhoneの共有メニューへ送信。最後の着信音設定は、そのメニューから自分で行います。", note: "保存 · iPhoneの共有メニュー" },
    ],
    privacyLabel: "自分の音は、自分のiPhoneの中に", privacyTitle: "音楽ファイルを\n預けなくても大丈夫。",
    privacyBody: "波形解析から編集、試聴、書き出しまでiPhone内で処理します。音声を開発者のサーバーに送信せず、アカウント登録や広告・追跡SDKもありません。",
    privacyTags: ["アカウント不要", "サーバー送信なし", "広告・追跡なし"],
    faqTitle: "始める前に", faqs: [
      { question: "ストリーミングアプリの曲も使えますか？", answer: "DRMで保護されたストリーミング音楽は編集できません。所有し、利用許可のあるMP3、M4A、AAC、WAVなどのDRMフリー音声ファイルを用意してください。" },
      { question: "アプリが自動で着信音を変更しますか？", answer: "アプリは着信音ファイルを作成し、iPhoneの共有メニューへ渡します。システムの着信音を自動変更することはできず、最後の設定は自分で行います。表示される項目はiOSや端末の環境によって異なる場合があります。" },
      { question: "どの端末で使えますか？", answer: "iOS 26以降のiPhoneで無料で使えます。ファイルはM4A形式で保存され、選択できる長さは最大30秒です。" },
    ],
    finalTitle: "次の電話は、\n自分で選んだ音で。", support: "使い方", privacy: "プライバシーポリシー", back: "アプリ一覧に戻る",
  },
} satisfies Record<Locale, object>;
